import turtle as t
t.setposition(0,0)
t.speed(1000)
t.pencolor('red')
t.up()
t.down()
t.fillcolor('red')
t.begin_fill()
t.circle(150,85)
t.end_fill()
t.pencolor('deep sky blue')
t.fillcolor('deep sky blue')
t.begin_fill()
t.circle(150,95)
t.end_fill()
t.pencolor('blue')
t.fillcolor('blue')
t.begin_fill()
t.circle(150,35)
t.end_fill()
t.pencolor('green')
t.fillcolor('green')
t.begin_fill()
t.circle(150,65)
t.end_fill()
t.pencolor('orange')
t.fillcolor('orange')
t.begin_fill()
t.circle(150,80)
t.end_fill()
t.left(90)
t.begin_fill()
t.forward(150)
t.left(100)
t.forward(150)
t.end_fill()

t.fillcolor('green')
t.begin_fill()
t.pencolor('white')
t.back(150)
t.right(65)
t.forward(150)
t.end_fill()

t.fillcolor('blue')
t.begin_fill()
t.back(150)
t.right(35)
t.forward(150)
t.end_fill()

t.fillcolor('deep sky blue')
t.begin_fill()
t.back(150)
t.right(95)
t.forward(150)
t.end_fill()

t.fillcolor('red')
t.begin_fill()
t.back(150)
t.right(85)
t.forward(150)
t.end_fill()

t.setposition(40,-30)
t.color('black')
t.write('B',move=False, align="left", font=("Arial", 17, "normal"))
t.up()
t.setposition(150,180)
t.down()
t.write('A',move=False, align="left", font=("Arial", 17, "normal"))
t.up()
t.setposition(-30,300)
t.down()
t.write('E',move=False, align="left", font=("Arial", 17, "normal"))
t.up()
t.setposition(-140,230)
t.down()
t.write('D',move=False, align="left", font=("Arial", 17, "normal"))
t.up()
t.setposition(-120,20)
t.down()
t.write('C',move=False, align="left", font=("Arial", 17, "normal"))









t.done()
